# coding: utf-8

"""
    KCrud

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contact_api import ContactApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_get(self):
        """Test case for contact_get

        """
        pass

    def test_contact_id_delete(self):
        """Test case for contact_id_delete

        """
        pass

    def test_contact_id_get(self):
        """Test case for contact_id_get

        """
        pass

    def test_contact_id_put(self):
        """Test case for contact_id_put

        """
        pass

    def test_contact_post(self):
        """Test case for contact_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
